import Foundation

// The Patient and PatientListResponse types are now generated by UniFFI
// from pablo-core (see Generated/pablo_core.swift). This file adds Swift-only
// protocol conformances and computed properties that the UI layer needs.

extension Patient: Identifiable {
    /// Display name formatted as "LastName, FirstName".
    public var fullName: String {
        "\(lastName), \(firstName)"
    }
}
