import Foundation

// The Session, SessionStatus, VideoPlatform, SessionType, SessionSource, and
// PatientSummary types are generated by UniFFI from pablo-core
// (see Generated/pablo_core.swift). This file adds Swift-only protocol
// conformances needed by the UI layer.

extension Session: Identifiable {}

extension PatientSummary: Identifiable {}
